defaults:
  - ../../../base/reward-gt/ID/contrastive-comparison@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0901-reward-gt-contrastive-comparison-8gpu

stats_logger:
  wandb:
    group: 0901-reward-gt-8gpu
