defaults:
  - ../../../base/personality-gate-credit-penalty/OOD/error_focused@_global_
  - ../../alloc@_global_
  - ../base@_global_
  - _self_

trial_name: 0818-personality-gate-credit-penalty-bs4-error-focused-8gpu

stats_logger:
  wandb:
    group: 0818-personality-gate-credit-penalty-bs4-8gpu
