defaults:
  - ../../../base/reward-v3/ID/all@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0901-preference-v3-reward-v3-all-id-8gpu

stats_logger:
  wandb:
    group: 0901-preference-v3-reward-v3-8gpu
