defaults:
  - ../../../base/personality-gate-terminate/ID/deep@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0818-personality-gate-terminate-deep-8gpu

stats_logger:
  wandb:
    group: 0818-personality-gate-terminate-8gpu
