defaults:
  - ../../../base/reward-gt-1/ID/attempt-diagnosis@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0901-reward-gt-1-attempt-diagnosis-8gpu

stats_logger:
  wandb:
    group: 0901-reward-gt-1-8gpu
