defaults:
  - ../../../base/reward-gt-1/ID/subgoal-decomposition@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0901-reward-gt-1-subgoal-decomposition-8gpu

stats_logger:
  wandb:
    group: 0901-reward-gt-1-8gpu
