defaults:
  - ../2gpu/qwen8b-qwen1.7b-math-pre-aleak-paw-cmae-wmrl050@_global_
  - _self_

cluster:
  n_gpus_per_node: 8

rollout:
  backend: "sglang:d4p1t1"

actor:
  backend: "fsdp:d4p1t1"
  mb_spec:
    max_tokens_per_mb: 24576

ref:
  mb_spec:
    max_tokens_per_mb: 24576
