defaults:
  - ../../../base/reward-gt-2/OOD/independent-verification@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0901-reward-gt-2-independent-verification-8gpu

stats_logger:
  wandb:
    group: 0901-reward-gt-2-8gpu
