experiment_name: hanabi-grpo
trial_name: trial0

seed: 1
enable_offload: false
total_train_epochs: 1
tokenizer_path: ${actor.path}

# Hanabi-specific options
teacher_server_addrs: ""
teacher_tokenizer_path: ""
teacher_api_key: ""
teacher_api_model: ""
student_api_key: ""
student_api_model: ""
misplay_penalty_factor: 1.0
use_question_tokens: true
env_kwargs: null

cluster:
  n_nodes: 2
  n_gpus_per_node: 8
  fileroot: /storage/openpsi/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /storage/openpsi/experiments

allocation_mode: sglang:d8p1t1+d8p1t1

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 64
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 4
  enable_rollout_tracing: false

# Generation hyperparameters
# In Hanabi rollouts, keep max_new_tokens high to capture multi-turn dialogs.
gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: 2048
  greedy: false
  temperature: 0.8

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: /storage/openpsi/models/Qwen__Qwen2.5-7B-Instruct
  # path: /storage/openpsi/experiments/checkpoints/admin/xmy-hanabi-sft-2/sft-7b-4-nodes-new/default/epoch0epochstep1140globalstep1140
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer:
    type: adam
    lr: 5e-6
    gradient_clipping: 1.0
    lr_scheduler_type: cosine
    min_lr_ratio: 0.6
    warmup_steps_proportion: 0
  group_size: ${gconfig.n_samples}
  eps_clip: 0.4
  temperature: ${gconfig.temperature}
  reward_scaling: 1.0
  reward_bias: 0.0
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0
  sft_reg: 1.0
  max_new_tokens: ${gconfig.max_new_tokens}

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer: null

# SGLang
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: null
  context_length: 32768
  mem_fraction_static: 0.8

vllm:
  model: ${actor.path}
  seed: ${seed}
  skip_tokenizer_init: false
  dtype: ${actor.dtype}
  max_model_len: 32768
  gpu_memory_utilization: 0.8

# datasets
train_dataset:
  batch_size: 512
  pin_memory: true
  num_workers: 4
  path: /storage/openpsi/users/xmy/inclusionAI/AReaL/data/Hanabi_placeholder_512.jsonl
  type: rl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 50
  freq_secs: 3600

recover:
  mode: auto
  retries: 5
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 10
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: null
  freq_steps: 1
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: online

launcher:
  inference_server_cpus_per_gpu: 4
  inference_server_mem_per_gpu: 32768
  trainer_cpus_per_gpu: 4
  trainer_mem_per_gpu: 32768
  slurm:
    mount: /storage:/storage
    trainer_image: /storage/openpsi/images/areal-latest.sif
    inference_server_image: /storage/openpsi/images/areal-latest.sif
  trainer_env_vars: WANDB_API_KEY=local-667d8d7f101dad4eb9597d718d0c68f40e3792f9,WANDB_BASE_URL=http://8.150.1.98:8080