defaults:
  - ../../../base/personality-gate-credit/ID/deep@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0818-personality-gate-credit-deep-8gpu

stats_logger:
  wandb:
    group: 0818-personality-gate-credit-8gpu
