defaults:
  - ../../../base/personality-gate-credit-penalty/ID/contrasting_cases@_global_
  - ../../alloc@_global_
  - _self_

trial_name: 0818-personality-gate-credit-penalty-contrasting-cases-8gpu

stats_logger:
  wandb:
    group: 0818-personality-gate-credit-penalty-8gpu
